# Generated by Django 3.1.1 on 2024-04-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zapatilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('azul', 'Azul')], max_length=20)),
                ('talla_minima', models.FloatField()),
                ('talla_maxima', models.FloatField()),
                ('marca', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
