# Generated by Django 3.1.1 on 2024-04-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatilla',
            name='condicion',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='disciplina',
            field=models.CharField(default='Running', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='genero',
            field=models.CharField(default='Hombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='material_del_forro',
            field=models.CharField(default='Textil', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='material_principal',
            field=models.CharField(default='Textil', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='pais_de_origen',
            field=models.CharField(default='China', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='color',
            field=models.CharField(choices=[('blanco', 'Blanco'), ('negro', 'Negro'), ('azul', 'Azul'), ('rojo', 'Rojo'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('gris', 'Gris')], max_length=20),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='marca',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('asics', 'Asics'), ('under armour', 'Under Armour'), ('new balance', 'New Balance'), ('reebok', 'Reebok')], max_length=50),
        ),
    ]
